permissions:
  contents: read
  deployments: read

name: Deployment Logger

on:
  deployment_status

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send deployment status to Discord
        uses: tsickert/discord-webhook@v7.0.0
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          embed-title: Deployment ${{ github.event.deployment_status.state }}
          embed-url: ${{ github.event.deployment_status.target_url }}
          embed-description: |
            **Repository:** [${{ github.repository }}](https://github.com/${{ github.repository }})  
            **Environment:** ${{ github.event.deployment.environment }}  
            **Status:** ${{ github.event.deployment_status.state }}  
          embed-color: ${{ github.event.deployment_status.state == 'success' && 3066993 || github.event.deployment_status.state == 'failure' && 15158332 || 16776960 }}
          embed-author-name: ${{ github.event.deployment.creator.login }}
          embed-author-url: https://github.com/${{ github.event.deployment.creator.login }}
          embed-thumbnail-url: ${{ github.event.sender.avatar_url }}
          embed-timestamp: ${{ github.event.deployment_status.updated_at }}
          embed-footer-text: Automated by GitHub Actions
